---
- name: delete Scaleway instance
  become: no
  environment:
    SCW_ACCESS_KEY: "{{ SCW_ACCESS_KEY }}"
    SCW_SECRET_KEY: "{{ SCW_SECRET_KEY }}"
    TF_VAR_project_id: "{{ PROJECT_ID }}"  
  terraform:
    force_init: yes
    project_path: "{{ playbook_dir }}/terraform"
    backend_config:
      path: "{{ playbook_dir }}/terraform/terraform.tfstate"
    state: absent
  register: _scw


  #- name: wait until ssh at EC2 available
  #  command: "sshpass -p nano ssh -o StrictHostKeyChecking=no -o PasswordAuthentication=yes -o User='ubuntu' -o ConnectTimeout=10 {{ _vpn.outputs['vpn_public_ip']['value'] }} echo ok"
  #  register: _instance_available
  #  until: _instance_available.stdout == "ok"
  #  retries: 10
  #  delay: 10
