- name: kubeadm token ...
  command: "kubeadm token create --print-join-command --ttl 0"
  register: _join_token
  tags:
    - k8s_init
  delegate_to: "{{ groups['master_group'][0] }}"

- name: print kubeadm token
  debug:
    msg: "{{ _join_token.stdout }}"

- name: set join command as ansible facts
  set_fact:
    _join_command: "{{ _join_token.stdout }}"

- name: join to a single node Kubernetes cluster
  command: "{{ _join_command }} --cri-socket=/run/containerd/containerd.sock"

