---
- name: generate an OpenSSH rsa keypair to be used by Terraform
  become: no
  community.crypto.openssh_keypair:
    path: "{{ playbook_dir }}/ssh/id_rsa"
    size: 4096

- name:
  tags:
    - k8s_init
  block:
    - name: set ansible facts
      vars:
        - _query_master_public_ip: "outputs.master_ipv4.value"
        - _query_node_public_ip: "outputs.node_ipv4.value"
      set_fact:
        _master_ip: "{{ lookup('file', '{{ playbook_dir }}/terraform/terraform.tfstate') | from_json | json_query(_query_master_public_ip)}}"
        _node_ip: "{{ lookup('file', '{{ playbook_dir }}/terraform/terraform.tfstate') | from_json | json_query(_query_node_public_ip)}}"

    - name: printing compound _master_ip and _node_ip 
      debug:
        msg: "{{ _master_ip }} {{ _node_ip}}"

    - name: check whether Scaleway istances already provisioned (no terrafrom run needed)
      command: "ssh -i {{ playbook_dir }}/ssh/id_rsa -o StrictHostKeyChecking=no -o PasswordAuthentication=yes -o User='ubuntu' -o ConnectTimeout=10 {{ item .split(':')[0]}} echo ok"
      register: _instance_available
      until: _instance_available.stdout == "ok"
      retries: 3
      delay: 10
      changed_when: no
      loop:
        - "{{ _master_ip }}"
        - "{{ _node_ip }}"

    - name: Adding Kubernetes master and node host to ansible inventory on the fly
      add_host:
        name: "{{ item.split(':')[1] }}"  # the mane of server
        groups: "{{ 'master_group' if item.split(':')[1]=='master' else 'node_group' }}"
        ansible_host: "{{ item.split(':')[0] }}"
        ansible_user: "root"
        ansible_connection: "ssh"
        ansible_ssh_common_args: "-o StrictHostKeyChecking=no"
        ansible_ssh_private_key_file: "{{ playbook_dir }}/ssh/id_rsa"
      loop:
        - "{{ _master_ip }}"
        - "{{ _node_ip }}"
      register: _inv

    - name: inventory on the fly
      debug:
        msg: "{{ _inv }}"

  rescue:
    # ***************************************************
    # Run Terraform code if block above fails | first run
    # ***************************************************
    - name: provision Scaleway instance
      become: no
      environment:
        SCW_ACCESS_KEY: "{{ SCW_ACCESS_KEY }}"
        SCW_SECRET_KEY: "{{ SCW_SECRET_KEY }}"
        TF_VAR_project_id: "{{ PROJECT_ID }}"  
      terraform:
        force_init: yes
        project_path: "{{ playbook_dir }}/terraform"
        backend_config:
          path: "{{ playbook_dir }}/terraform/terraform.tfstate"
        # state: present
      register: _scw

    - name: public ipv4 address of Kubernetes master/node
      debug:
        msg: "{{ _scw.outputs[{{ item }}]['value'].split(':')[0] }}"
      loop:
        - "master_ipv4"
        - "node_ipv4"
        
    - name: Adding host to ansible inventory on the fly
      add_host:
        name: "{{ _scw.outputs[{{ item }}]['value'].split(':')[1] }}"  # the mane of server
        groups: "{{ 'master_group' if _scw.outputs[{{ item }}]['value'].split(':')[1]=='master' else 'node_group' }}"
        ansible_host: "{{ _scw.outputs['{{ item }}']['value'].split(':')[0] }}"
        ansible_user: "root"
        ansible_connection: "ssh"
        ansible_ssh_common_args: "-o StrictHostKeyChecking=no"
        ansible_ssh_private_key_file: "{{ playbook_dir }}/ssh/id_rsa"
      loop:
        - "master_ipv4"
        - "node_ipv4"
      register: _inv

    - name: inventory on the fly
      debug:
        msg: "{{ _inv }}"

    - name: wait until ssh at Scaleway available
      command: "ssh -i {{ playbook_dir }}/ssh/id_rsa -o StrictHostKeyChecking=no -o PasswordAuthentication=yes -o User='ubuntu' -o ConnectTimeout=10 {{ _scw.outputs[{{ item }}]['value'].split(':')[0] }} echo ok"
      register: _instance_available
      until: _instance_available.stdout == "ok"
      retries: 10
      delay: 10
      loop:
        - "master_ipv4"
        - "node_ipv4"


