---
- hosts: localhost
  gather_facts: no
  tasks:
    - name: generate an OpenSSH rsa keypair to be used by Terraform
      become: no
      community.crypto.openssh_keypair:
        path: "{{ playbook_dir }}/ssh/id_rsa"
        size: 4096

- hosts: localhost
  gather_facts: no
  become: no
  roles:
    - provision-scw-instance

- hosts: scw
  gather_facts: yes
  become: no
  roles:
    - setup_k8s


