---
# Provision Scaleway instance (if does not exist)
- hosts: localhost
  gather_facts: no
  become: no
  roles:
    - provision-scw-instance

# Setup Kubernetes master/node 
- hosts: ["master_group", "node_group"]
  gather_facts: yes
  become: no
  roles:
    - common_settings

# Setup Kubernetes master via kubeadm init ...
- hosts: master_group
  gather_facts: yes
  become: no
  roles:
    - init_k8s

# Join Kubenretes node kubeadm join ...
- hosts: node_group
  gather_facts: yes
  become: no
  roles:
    - join_k8s
      #
# Try to deploy istio ...
- hosts: master_group
  gather_facts: yes
  become: no
  roles:
    - istio
