---
# Provision Scaleway instance (if does not exist)
- hosts: localhost
  gather_facts: no
  become: no
  roles:
    - provision-scw-instance

# Setup Kubernetes cluster via kubeadm 
- hosts: scw
  gather_facts: yes
  become: no
  roles:
    - setup_k8s


