- name: kubeadm init ...
  command: |
    kubeadm init \
      --kubernetes-version={{ KUBE_VERSION }} \
      --ignore-preflight-errors=NumCPU,Mem \
      --skip-token-print \
      --pod-network-cidr 192.168.0.0/16 \
      --cri-socket "{{ 'unix:///var/run/crio/crio.sock' if container_runtime=='crio' else 'unix:///run/containerd/containerd.sock' }}"
  tags:
    - k8s_init

- name: create a directory ~/.kube
  ansible.builtin.file:
    path: ~/.kube
    state: directory
    mode: '0755'
  tags:
    - k8s_init

- name: copy file with owner and permissions
  shell: "yes | cp -i /etc/kubernetes/admin.conf ~/.kube/config"
  tags:
    - k8s_init

  #- name: install cilium binary
  #  vars:
  #  - _cli_arch: amd64
  #  shell: |
  #    CILIUM_CLI_VERSION=$(curl -s https://raw.githubusercontent.com/cilium/cilium-cli/master/stable.txt)
  #    curl -L --fail "https://github.com/cilium/cilium-cli/releases/download/$CILIUM_CLI_VERSION/cilium-linux-{{ _cli_arch }}.tar.gz"
  #    tar xzvfC "cilium-linux-{{ _cli_arch }}.tar.gz" /usr/local/bin
  #    rm "cilium-linux-{{ _cli_arch }}.tar.gz"
  #
  #- name: cilium install
  #  shell: |
  #    cilium install --helm-set kubeProxyReplacement=strict

- name: kubectl apply -f .../calico.yaml
  command: kubectl apply -f {{ calico_url }}
  tags:
    - k8s_init

- name: kubectl rollout restart deployment coredns --namespace kube-system
  command: kubectl rollout restart deployment coredns --namespace kube-system
  tags:
    - istio
